"""Figure/data guide tables for the HTML report.

Pure data extracted from ``generate_report.py``.
"""

from __future__ import annotations


STAGE_LABELS = {
    "01_qc": "质控",
    "02_doublets": "双细胞检测",
    "03_cluster": "聚类",
    "04_annotation": "细胞注释",
    "05_deg": "差异表达",
    "06_enrichment": "富集分析",
    "07_ml": "机器学习",
    "08_publication": "高级分析与发表图",
    "09_cellchat": "细胞通讯",
}

FIGURE_GUIDE = {
    "fig_01_qc_raw_violin.png": ("QC 小提琴图（原始）", "过滤前 nFeature、nCount、percent.mt、percent.ribo、percent.hb 的分布，用于识别低质量细胞、核糖体/血红蛋白污染和数据批次差异。"),
    "fig_01_qc_filtered_violin.png": ("QC 小提琴图（过滤后）", "过滤后的 QC 指标分布，确认阈值是否合理、主要细胞群是否保留。"),
    "fig_48_qc_pvalue_comparison.png": ("QC 质控差异度 P 值图", "以 Wilcoxon 秩和检验 P 值衡量原始/过滤后 QC 指标（含核糖体和血红蛋白比例）在不同条件间的差异程度。"),
    "fig_49_qc_umi_feature_correlation.png": ("UMI 与基因数关系 QC 图", "以 log1p 尺度展示 UMI 数与基因数的线性关系，标记通过/未通过当前 QC 阈值的细胞，用于识别远离主流关系的异常细胞。"),
    "fig_02_doublet_scores.png": ("双细胞得分图", "scDblFinder 双细胞得分的分布，用于判断双细胞分类边界。"),
    "fig_03_umap_clusters.png": ("UMAP 聚类图", "Seurat 聚类在 UMAP 上的结构，检查分群是否清晰、是否存在过度分割。"),
    "fig_04_umap_condition.png": ("UMAP 分组图", "不同条件下细胞在 UMAP 上的分布，检查分组偏移和批次效应。"),
    "fig_05_umap_annotation.png": ("UMAP 注释图", "细胞类型注释在 UMAP 上的分布，验证注释与聚类结构的一致性。"),
    "fig_06_dotplot_markers.png": ("Marker 基因 DotPlot", "marker 基因在各细胞类型中的表达比例和表达量，用于验证注释。"),
    "fig_07_annotation_confusion_heatmap.png": ("注释混淆矩阵热图", "自动注释与发布注释之间的一致性，识别容易混淆的细胞类型。"),
    "fig_08_volcano.png": ("差异表达火山图", "以 log2FC 和校正 P 值展示差异基因，观察上调和下调基因的显著性分布。"),
    "fig_09_deg_heatmap.png": ("Top DEG 热图", "Top 差异基因在样本/条件下的表达模式，用于查看差异基因的整体趋势。"),
    "fig_09_deg_horizontal_violin.png": ("Top DEG 横向小提琴图（P 值）", "按校正 P 值排序的差异最显著基因，横向对比两组表达分布并标注 P 值。"),
    "fig_10_go_up.png": ("GO BP 富集图（上调）", "上调基因的 GO 生物过程富集结果，查看显著富集的通路。"),
    "fig_11_go_down.png": ("GO BP 富集图（下调）", "下调基因的 GO 生物过程富集结果，查看显著富集的通路。"),
    "fig_12_kegg_up.png": ("KEGG 富集图（上调）", "上调基因的 KEGG 通路富集结果。"),
    "fig_13_kegg_down.png": ("KEGG 富集图（下调）", "下调基因的 KEGG 通路富集结果。"),
    "fig_14_pca.png": ("PCA 分组图", "主成分空间中的样本/细胞分布，观察主要变异来源。"),
    "fig_15_elbow.png": ("主成分 Elbow 图", "各主成分解释的方差比例，用于选择后续分析的主成分数。"),
    "fig_16_featureplot_markers.png": ("Marker 基因 FeaturePlot", "marker 基因在 UMAP 上的表达位置，验证细胞类型注释。"),
    "fig_17_marker_violin.png": ("Marker 基因小提琴图", "marker 基因在不同细胞类型中的表达分布。"),
    "fig_50_marker_ridgeplot.png": ("Marker 基因峰峦图", "marker 基因表达量按细胞类型绘制的 RidgePlot，用于横向比较表达分布和特异性。"),
    "fig_51_marker_stacked_violin.png": ("Marker 基因堆叠小提琴图", "多个 marker 基因按细胞类型堆叠排列的小提琴图，便于快速核对注释 marker 模式。"),
    "fig_18_celltype_proportion.png": ("细胞类型比例堆叠图", "不同样本/条件下细胞类型构成的变化。"),
    "fig_19_condition_proportion.png": ("分组构成比例图", "不同分组中细胞类型的比例对比。"),
    "fig_20_gsea_go.png": ("GSEA GO BP 富集图", "GO 生物过程的 GSEA 富集曲线，查看通路的整体上调/下调方向。"),
    "fig_21_gsea_kegg.png": ("GSEA KEGG 富集图", "KEGG 通路的 GSEA 富集曲线。"),
    "fig_22_go_network.png": ("GO BP 通路网络图（Top5 核心 + 5 延伸）", "上调基因 GO 富集结果经 p.adjust 筛选后保留前 5 个核心通路，并追加最佳 5 个延伸通路的基因-通路关系网络。"),
    "fig_23_kegg_network.png": ("KEGG 通路网络图（Top5 核心 + 5 延伸）", "上调基因 KEGG 富集结果经 p.adjust 筛选后保留前 5 个核心通路，并追加最佳 5 个延伸通路的基因-通路关系网络。"),
    "fig_46_go_top5.png": ("GO BP 筛选后 Top5 富集图", "上调基因 GO 富集结果按 p.adjust 排序的前 5 条通路气泡图。"),
    "fig_47_kegg_top5.png": ("KEGG 筛选后 Top5 富集图", "上调基因 KEGG 富集结果按 p.adjust 排序的前 5 条通路气泡图。"),
    "fig_24_ml_feature_importance.png": ("ML 特征重要性图", "分类模型中的重要基因/特征，用于筛选关键变量。"),
    "fig_25_ml_shap.png": ("SHAP 可解释性图", "特征对模型预测的方向和贡献，解释分类结果。"),
    "fig_26_cellcycle_umap.png": ("细胞周期 UMAP", "细胞周期阶段在 UMAP 上的分布，检查细胞周期对聚类的干扰。"),
    "fig_27_cellcycle_proportion.png": ("细胞周期比例图", "不同细胞类型/分组中的细胞周期比例。"),
    "fig_28_umap_sample.png": ("UMAP 按样本", "样本来源在 UMAP 上的分布，评估样本混合和批次效应。"),
    "fig_29_doublet_rate_sample.png": ("样本双细胞率图", "每个样本的双细胞率，识别异常样本。"),
    "fig_30_sample_proportion.png": ("样本细胞类型比例图", "每个样本的细胞类型组成，检查样本间异质性。"),
    "fig_31_cluster_marker_heatmap.png": ("聚类 Marker 热图", "各聚类 marker 基因的表达模式，用于重新定义聚类标签。"),
    "fig_32_cluster_marker_dotplot.png": ("聚类 Marker DotPlot", "各聚类 marker 的表达比例和水平。"),
    "fig_33_signature_scores_umap.png": ("功能签名 UMAP", "增殖、EMT、缺氧等功能签名在 UMAP 上的分布。"),
    "fig_34_signature_scores_boxplot.png": ("功能签名箱线图", "不同条件下功能签名得分的差异。"),
    "fig_35_celltype_abundance_effect.png": ("细胞类型丰度变化图", "细胞类型丰度在组间的变化方向和显著性。"),
    "fig_36_cnv_heatmap.png": ("推断 CNV 热图", "基于表达推断的拷贝数变异模式，用于区分恶性/非恶性细胞。"),
    "fig_37_singler_umap.png": ("SingleR 注释 UMAP", "SingleR 参考注释在 UMAP 上的分布。"),
    "fig_38_singler_confusion_heatmap.png": ("SingleR 混淆矩阵热图", "SingleR 注释与现有注释的一致性。"),
    "fig_39_trajectory_umap.png": ("拟时序轨迹图", "拟时序分析结果，查看细胞分化轨迹。"),
    "fig_40_cellchat_network.png": ("CellChat 通讯网络图", "细胞类型之间的配体受体通讯网络。"),
    "fig_41_cellchat_heatmap.png": ("CellChat 通讯热图", "细胞类型对之间的通讯强度。"),
    "fig_42_cellchat_bubble.png": ("CellChat 配体受体气泡图", "关键配体受体对在细胞类型间的通讯关系。"),
    "fig_43_ml_confusion_matrix.png": ("ML 混淆矩阵", "分类模型的预测混淆情况，查看具体错分。"),
    "fig_44_ml_roc_pr.png": ("ML ROC 与 PR 曲线", "分类模型的 ROC 和 PR 性能，评估分类能力。"),
    "fig_45_ml_cv_scores.png": ("ML 交叉验证得分图", "交叉验证得分的分布，评估模型稳定性。"),
}

DATA_GUIDE = {
    "fig_01_qc_metrics.csv": ("QC 指标表", "每细胞的 nFeature、nCount、percent.mt、percent.ribo、percent.hb 以及样本/分组信息，用于检查过滤前后细胞质量。"),
    "qc_metrics.csv": ("QC 指标表", "每细胞的 nFeature、nCount、percent.mt、percent.ribo、percent.hb 以及样本/分组信息，用于检查过滤前后细胞质量。"),
    "fig_01_qc_thresholds.csv": ("QC 过滤规则表", "每条 QC 规则的上下限、按该规则移除的细胞数和比例。"),
    "fig_49_qc_umi_feature_correlation_stats.csv": ("UMI 与基因数关系统计表", "log-log 回归斜率、相关系数、残差 MAD、建议复核细胞数等 raw/filtered 两阶段统计。"),
    "fig_02_doublet_results.csv": ("双细胞结果表", "每细胞的双细胞得分和分类结果，用于评估双细胞去除。"),
    "doublet_results.csv": ("双细胞结果表", "每细胞的双细胞得分和分类结果，用于评估双细胞去除。"),
    "fig_05_16_17_cell_annotations.csv": ("细胞注释表", "每细胞的聚类、细胞类型注释和样本分组信息。"),
    "cell_annotations.csv": ("细胞注释表", "每细胞的聚类、细胞类型注释和样本分组信息。"),
    "fig_07_annotation_confusion.csv": ("注释混淆矩阵", "自动注释与发布注释的交叉计数。"),
    "annotation_confusion.csv": ("注释混淆矩阵", "自动注释与发布注释的交叉计数。"),
    "fig_08_deg_all.csv": ("全部差异表达基因", "所有基因的差异表达统计，包括 log2FC、P 值和校正 P 值。"),
    "deg_all.csv": ("全部差异表达基因", "所有基因的差异表达统计，包括 log2FC、P 值和校正 P 值。"),
    "fig_09_deg_significant.csv": ("显著差异表达基因", "达到显著性阈值的差异基因列表。"),
    "deg_significant.csv": ("显著差异表达基因", "达到显著性阈值的差异基因列表。"),
    "fig_09_deg_horizontal_violin.csv": ("Top DEG 横向小提琴图数据", "横向小提琴图对应的基因、差异倍数和校正 P 值。"),
    "fig_10_enrichment_up_go.csv": ("上调基因 GO 富集表", "上调基因的 GO 生物过程富集结果。"),
    "enrichment_up_go.csv": ("上调基因 GO 富集表", "上调基因的 GO 生物过程富集结果。"),
    "fig_11_enrichment_down_go.csv": ("下调基因 GO 富集表", "下调基因的 GO 生物过程富集结果。"),
    "enrichment_down_go.csv": ("下调基因 GO 富集表", "下调基因的 GO 生物过程富集结果。"),
    "fig_12_enrichment_up_kegg.csv": ("上调基因 KEGG 富集表", "上调基因的 KEGG 通路富集结果。"),
    "enrichment_up_kegg.csv": ("上调基因 KEGG 富集表", "上调基因的 KEGG 通路富集结果。"),
    "fig_13_enrichment_down_kegg.csv": ("下调基因 KEGG 富集表", "下调基因的 KEGG 通路富集结果。"),
    "enrichment_down_kegg.csv": ("下调基因 KEGG 富集表", "下调基因的 KEGG 通路富集结果。"),
    "fig_18_19_celltype_proportion_stats.csv": ("细胞类型比例统计", "细胞类型比例的统计和组间比较结果。"),
    "fig_26_27_cell_cycle_scores.csv": ("细胞周期打分", "每细胞的 S 和 G2M 期打分。"),
    "cell_cycle_scores.csv": ("细胞周期打分", "每细胞的 S 和 G2M 期打分。"),
    "fig_29_doublet_rate_by_sample.csv": ("样本双细胞率", "每个样本的双细胞数量、比例和去双细胞前后细胞数。"),
    "doublet_rate_by_sample.csv": ("样本双细胞率", "每个样本的双细胞数量、比例和去双细胞前后细胞数。"),
    "fig_16_17_31_32_cluster_markers.csv": ("聚类 marker 基因", "每个聚类的 marker 基因及统计信息。"),
    "cluster_markers.csv": ("聚类 marker 基因", "每个聚类的 marker 基因及统计信息。"),
    "fig_33_34_35_signature_scores.csv": ("功能签名打分", "增殖、EMT、缺氧等签名在每细胞中的得分。"),
    "signature_scores.csv": ("功能签名打分", "增殖、EMT、缺氧等签名在每细胞中的得分。"),
    "fig_36_cnv_heatmap.csv": ("推断 CNV 热图矩阵", "基于染色体窗口均值推断的 CNV 矩阵。"),
    "cnv_heatmap.csv": ("推断 CNV 热图矩阵", "基于染色体窗口均值推断的 CNV 矩阵。"),
    "fig_37_singleR_annotations.csv": ("SingleR 注释表", "SingleR 参考注释和打分。"),
    "singleR_annotations.csv": ("SingleR 注释表", "SingleR 参考注释和打分。"),
    "fig_38_singleR_confusion.csv": ("SingleR 混淆矩阵", "SingleR 注释与现有注释的交叉计数。"),
    "singleR_confusion.csv": ("SingleR 混淆矩阵", "SingleR 注释与现有注释的交叉计数。"),
    "fig_39_trajectory_pseudotime.csv": ("拟时序结果", "每细胞的拟时序值和轨迹信息。"),
    "fig_40_cellchat_communication.csv": ("CellChat 通讯矩阵", "细胞类型之间的通讯数量或强度。"),
    "fig_40_cellchat_communication_weight.csv": ("CellChat 通讯权重", "细胞类型之间的通讯权重。"),
    "fig_42_cellchat_pathways.csv": ("CellChat 通路表", "CellChat 识别的配体受体通路。"),
    "fig_24_ml_feature_importance.csv": ("ML 特征重要性", "分类模型的特征重要性排序。"),
    "ml_feature_importance.csv": ("ML 特征重要性", "分类模型的特征重要性排序。"),
    "fig_43_44_45_ml_classification_results.csv": ("ML 分类预测", "每个样本或细胞的预测结果。"),
    "ml_classification_results.csv": ("ML 分类预测", "每个样本或细胞的预测结果。"),
    "fig_43_44_45_ml_classification_report.csv": ("ML 分类报告", "分类模型的精确率、召回率、F1 等指标。"),
    "ml_classification_report.csv": ("ML 分类报告", "分类模型的精确率、召回率、F1 等指标。"),
    "sample_annotations.csv": ("样本分组表", "样本与疾病分组/条件的对应关系。"),
    "liver_cancer_seurat.rds": ("Seurat 对象", "完整单细胞 Seurat 对象，可用于下游重分析和复现。"),
}

FIGURE_DATA_MAP = {
    "fig_01_qc_raw_violin.png": [
        "fig_01_qc_metrics.csv",
        "qc_metrics.csv",
        "fig_01_qc_thresholds.csv",
    ],
    "fig_01_qc_filtered_violin.png": [
        "fig_01_qc_metrics.csv",
        "qc_metrics.csv",
        "fig_01_qc_thresholds.csv",
    ],
    "fig_48_qc_pvalue_comparison.png": [
        "fig_48_qc_pvalue_comparison.csv",
        "fig_01_qc_thresholds.csv",
    ],
    "fig_49_qc_umi_feature_correlation.png": [
        "fig_49_qc_umi_feature_correlation_stats.csv",
        "fig_01_qc_metrics.csv",
        "fig_01_qc_thresholds.csv",
    ],
    "fig_02_doublet_scores.png": [
        "fig_02_doublet_results.csv",
        "doublet_results.csv",
        "fig_29_doublet_rate_by_sample.csv",
        "doublet_rate_by_sample.csv",
    ],
    "fig_03_umap_clusters.png": [
        "fig_03_04_05_umap_coordinates.csv",
        "umap_coordinates.csv",
    ],
    "fig_04_umap_condition.png": [
        "fig_03_04_05_umap_coordinates.csv",
        "umap_coordinates.csv",
    ],
    "fig_05_umap_annotation.png": [
        "fig_03_04_05_umap_coordinates.csv",
        "umap_coordinates.csv",
        "fig_05_16_17_cell_annotations.csv",
        "cell_annotations.csv",
        "fig_07_annotation_confusion.csv",
        "annotation_confusion.csv",
    ],
    "fig_06_dotplot_markers.png": [
        "fig_05_16_17_cell_annotations.csv",
        "cell_annotations.csv",
        "fig_16_17_31_32_cluster_markers.csv",
        "cluster_markers.csv",
    ],
    "fig_07_annotation_confusion_heatmap.png": [
        "fig_07_annotation_confusion.csv",
        "annotation_confusion.csv",
        "fig_38_singleR_confusion.csv",
        "singleR_confusion.csv",
    ],
    "fig_08_volcano.png": [
        "fig_08_deg_all.csv",
        "deg_all.csv",
        "fig_09_deg_significant.csv",
        "deg_significant.csv",
    ],
    "fig_09_deg_heatmap.png": [
        "fig_09_deg_significant.csv",
        "deg_significant.csv",
        "fig_09_deg_horizontal_violin.csv",
    ],
    "fig_09_deg_horizontal_violin.png": [
        "fig_09_deg_horizontal_violin.csv",
        "fig_09_deg_significant.csv",
        "deg_significant.csv",
    ],
    "fig_10_go_up.png": ["fig_10_enrichment_up_go.csv", "enrichment_up_go.csv"],
    "fig_11_go_down.png": [
        "fig_11_enrichment_down_go.csv",
        "enrichment_down_go.csv",
    ],
    "fig_12_kegg_up.png": ["fig_12_enrichment_up_kegg.csv", "enrichment_up_kegg.csv"],
    "fig_13_kegg_down.png": [
        "fig_13_enrichment_down_kegg.csv",
        "enrichment_down_kegg.csv",
    ],
    "fig_14_pca.png": [
        "fig_03_04_05_umap_coordinates.csv",
        "umap_coordinates.csv",
        "sample_annotations.csv",
    ],
    "fig_15_elbow.png": ["sample_annotations.csv"],
    "fig_16_featureplot_markers.png": [
        "fig_05_16_17_cell_annotations.csv",
        "cell_annotations.csv",
        "fig_16_17_31_32_cluster_markers.csv",
        "cluster_markers.csv",
    ],
    "fig_17_marker_violin.png": [
        "fig_05_16_17_cell_annotations.csv",
        "cell_annotations.csv",
        "fig_16_17_31_32_cluster_markers.csv",
        "cluster_markers.csv",
    ],
    "fig_50_marker_ridgeplot.png": [
        "fig_05_16_17_cell_annotations.csv",
        "cell_annotations.csv",
        "fig_16_17_31_32_cluster_markers.csv",
        "cluster_markers.csv",
    ],
    "fig_51_marker_stacked_violin.png": [
        "fig_05_16_17_cell_annotations.csv",
        "cell_annotations.csv",
        "fig_16_17_31_32_cluster_markers.csv",
        "cluster_markers.csv",
    ],
    "fig_18_celltype_proportion.png": [
        "fig_18_19_celltype_proportion_stats.csv",
        "fig_18_19_30_cluster_composition.csv",
        "cluster_composition.csv",
        "fig_05_16_17_cell_annotations.csv",
        "cell_annotations.csv",
    ],
    "fig_19_condition_proportion.png": [
        "fig_18_19_celltype_proportion_stats.csv",
        "fig_18_19_30_cluster_composition.csv",
        "cluster_composition.csv",
    ],
    "fig_20_gsea_go.png": [
        "fig_20_gsea_go.csv",
        "gsea_go.csv",
        "fig_08_deg_all.csv",
        "deg_all.csv",
    ],
    "fig_21_gsea_kegg.png": [
        "fig_21_gsea_kegg.csv",
        "gsea_kegg.csv",
        "fig_08_deg_all.csv",
        "deg_all.csv",
    ],
    "fig_22_go_network.png": [
        "fig_10_enrichment_up_go.csv",
        "enrichment_up_go.csv",
    ],
    "fig_23_kegg_network.png": [
        "fig_12_enrichment_up_kegg.csv",
        "enrichment_up_kegg.csv",
    ],
    "fig_24_ml_feature_importance.png": [
        "fig_24_ml_feature_importance.csv",
        "ml_feature_importance.csv",
        "ml_model_summary.json",
    ],
    "fig_25_ml_shap.png": [
        "ml_model_summary.json",
        "fig_43_44_45_ml_classification_results.csv",
        "ml_classification_results.csv",
    ],
    "fig_26_cellcycle_umap.png": [
        "fig_26_27_cell_cycle_scores.csv",
        "cell_cycle_scores.csv",
    ],
    "fig_27_cellcycle_proportion.png": [
        "fig_26_27_cell_cycle_scores.csv",
        "cell_cycle_scores.csv",
    ],
    "fig_28_umap_sample.png": [
        "fig_03_04_05_umap_coordinates.csv",
        "umap_coordinates.csv",
        "sample_annotations.csv",
    ],
    "fig_29_doublet_rate_sample.png": [
        "fig_29_doublet_rate_by_sample.csv",
        "doublet_rate_by_sample.csv",
    ],
    "fig_30_sample_proportion.png": [
        "fig_18_19_30_cluster_composition.csv",
        "cluster_composition.csv",
        "sample_annotations.csv",
    ],
    "fig_31_cluster_marker_heatmap.png": [
        "fig_16_17_31_32_cluster_markers.csv",
        "cluster_markers.csv",
    ],
    "fig_32_cluster_marker_dotplot.png": [
        "fig_16_17_31_32_cluster_markers.csv",
        "cluster_markers.csv",
    ],
    "fig_33_signature_scores_umap.png": [
        "fig_33_34_35_signature_scores.csv",
        "signature_scores.csv",
    ],
    "fig_34_signature_scores_boxplot.png": [
        "fig_33_34_35_signature_scores.csv",
        "signature_scores.csv",
    ],
    "fig_35_celltype_abundance_effect.png": [
        "differential_abundance.csv",
        "fig_33_34_35_signature_scores.csv",
        "signature_scores.csv",
    ],
    "fig_36_cnv_heatmap.png": ["fig_36_cnv_heatmap.csv", "cnv_heatmap.csv"],
    "fig_37_singler_umap.png": [
        "fig_37_singleR_annotations.csv",
        "singleR_annotations.csv",
    ],
    "fig_38_singler_confusion_heatmap.png": [
        "fig_38_singleR_confusion.csv",
        "singleR_confusion.csv",
    ],
    "fig_39_trajectory_umap.png": ["fig_39_trajectory_pseudotime.csv"],
    "fig_40_cellchat_network.png": [
        "fig_40_cellchat_communication.csv",
        "fig_40_cellchat_communication_weight.csv",
    ],
    "fig_41_cellchat_heatmap.png": [
        "fig_40_cellchat_communication.csv",
        "fig_40_cellchat_communication_weight.csv",
    ],
    "fig_42_cellchat_bubble.png": ["fig_42_cellchat_pathways.csv"],
    "fig_43_ml_confusion_matrix.png": [
        "fig_43_44_45_ml_classification_report.csv",
        "ml_classification_report.csv",
        "fig_43_44_45_ml_classification_results.csv",
        "ml_classification_results.csv",
        "ml_model_summary.json",
    ],
    "fig_44_ml_roc_pr.png": [
        "fig_43_44_45_ml_classification_report.csv",
        "ml_classification_report.csv",
        "fig_43_44_45_ml_classification_results.csv",
        "ml_classification_results.csv",
        "ml_model_summary.json",
    ],
    "fig_45_ml_cv_scores.png": [
        "fig_43_44_45_ml_classification_report.csv",
        "ml_classification_report.csv",
        "fig_43_44_45_ml_classification_results.csv",
        "ml_classification_results.csv",
        "ml_model_summary.json",
    ],
    "fig_45_ml_calibration_curve.png": [
        "fig_43_44_45_ml_classification_report.csv",
        "ml_classification_report.csv",
    ],
    "fig_46_go_top5.png": ["fig_10_enrichment_up_go.csv", "enrichment_up_go.csv"],
    "fig_47_kegg_top5.png": ["fig_12_enrichment_up_kegg.csv", "enrichment_up_kegg.csv"],
}
