#!/usr/bin/env python3
"""Cytoscape network export helpers for the network toxicology module.

The module writes a self-contained XGMML network file with the standard
library, and optionally pushes the same C-T-P-D network into a running
Cytoscape instance through py4cytoscape/CyREST.
"""

from __future__ import annotations

import importlib.util
import logging
import time
import urllib.request
from pathlib import Path
from xml.sax.saxutils import quoteattr

import pandas as pd

from .utils import DockingError

LOG = logging.getLogger(__name__)

_NODE_FILL = {
    "compound": "#4C72B0",
    "target": "#DD8452",
    "disease": "#C44E52",
}
_NODE_SHAPE = {
    "compound": "ROUND_RECTANGLE",
    "target": "ELLIPSE",
    "disease": "HEXAGON",
}
_EDGE_FILL = {
    "compound_target": "#4C72B0",
    "disease_target": "#C44E52",
    "ppi": "#8C8C8C",
}


def cytoscape_running(base_url: str = "http://127.0.0.1:1234") -> bool:
    """Return whether a CyREST endpoint responds on the given base URL."""
    root = str(base_url or "http://127.0.0.1:1234").rstrip("/")
    probe = (
        root + "/version"
        if root.endswith("/v1")
        else root + "/v1/version"
    )
    try:
        with urllib.request.urlopen(probe, timeout=1.2) as resp:
            return bool(resp.status == 200)
    except Exception:
        return False


def write_xgmml_network(
    nodes_csv: str | Path,
    edges_csv: str | Path,
    out_path: str | Path,
    network_label: str = "Compound-Target-Disease Network",
) -> str:
    """Write Cytoscape-compatible XGMML from the C-T-P-D CSV tables."""
    nodes = pd.read_csv(nodes_csv, dtype=str).fillna("")
    edges = pd.read_csv(edges_csv, dtype=str).fillna("")
    if nodes.empty:
        raise DockingError("Cytoscape XGMML export needs at least one node")

    node_ids: dict[str, str] = {}
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<graph label='
        + quoteattr(str(network_label))
        + ' directed="0" xmlns="http://www.cs.rpi.edu/XGMML">',
        "<att name=\"name\" value=" + quoteattr(str(network_label)) + "/>",
        (
            "<att name=\"description\" "
            'value="Generated by the liver network toxicology pipeline."/>'
        ),
    ]
    for index, row in nodes.iterrows():
        node_id = str(row.get("node_id") or row.get("id") or index)
        mapped = f"n{len(node_ids) + 1}"
        node_ids[node_id] = mapped
        label = str(row.get("label") or node_id)
        node_type = str(row.get("node_type") or "target").lower()
        fill = _NODE_FILL.get(node_type, "#DD8452")
        shape = _NODE_SHAPE.get(node_type, "ELLIPSE")
        try:
            degree = float(row.get("ppi_degree") or 0)
        except ValueError:
            degree = 0.0
        if node_type == "compound":
            width, height = 110.0, 42.0
        elif node_type == "disease":
            width, height = 120.0, 48.0
        else:
            width = height = min(90.0, max(38.0, 34.0 + degree * 0.35))
        lines.append(f'<node label={quoteattr(label)} id="{mapped}">')
        for column, value in row.items():
            if column in ("node_id", "id"):
                continue
            lines.append(
                _att_element(str(column), str(value), _xgmml_type(column, value))
            )
        lines.append(
            '<graphics type="'
            + shape
            + f'" fill="{fill}" outline="#333333" width="2.0" w="{width:.1f}" h="{height:.1f}"/>'
        )
        lines.append("</node>")

    if not edges.empty:
        for _, row in edges.iterrows():
            source = str(row.get("source") or "")
            target = str(row.get("target") or "")
            if source not in node_ids or target not in node_ids:
                continue
            edge_type = str(row.get("edge_type") or "interacts_with")
            fill = _EDGE_FILL.get(str(edge_type).lower(), "#8C8C8C")
            label = f"{source} ({edge_type}) {target}"
            try:
                score = float(row.get("combined_score") or 0)
            except ValueError:
                score = 0.0
            if str(edge_type).lower() == "ppi" and score:
                width = min(6.0, max(1.5, score / 1000.0 * 5.0))
            else:
                width = 2.5 if str(edge_type).lower() != "ppi" else 2.0
            lines.append(
                f'<edge label={quoteattr(label)} source="{node_ids[source]}" '
                f'target="{node_ids[target]}">'
            )
            for column, value in row.items():
                if column in ("source", "target"):
                    continue
                lines.append(
                    _att_element(str(column), str(value), _xgmml_type(column, value))
                )
            lines.append(
                f'<graphics fill="{fill}" width="{width:.1f}"/>'
            )
            lines.append("</edge>")
    lines.append("</graph>")

    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)


def export_network_to_cytoscape(
    nodes_csv: str | Path,
    edges_csv: str | Path,
    out_dir: str | Path,
    *,
    network_title: str = "Compound-Target-Disease Network",
    base_url: str = "http://127.0.0.1:1234",
    layout: str = "cose",
    save_session: bool = False,
    mode: str = "auto",
) -> dict:
    """Create a styled Cytoscape network when a CyREST server is available.

    ``mode`` may be ``auto`` (XGMML-only fallback is acceptable), ``on``
    (raise when Cytoscape/py4cytoscape is unavailable) or ``off``.
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    if str(mode).lower() == "off":
        return {"status": "off"}

    if importlib.util.find_spec("py4cytoscape") is None:
        reason = (
            "py4cytoscape is not installed; run "
            "launchers\\install_dock_dependencies.bat or "
            "pip install py4cytoscape"
        )
        if str(mode).lower() == "on":
            raise DockingError(reason)
        return {
            "status": "xgmml_only",
            "reason": reason,
        }

    if not cytoscape_running(base_url):
        reason = (
            "Cytoscape CyREST is not running on "
            + str(base_url)
            + "; start Cytoscape with: cytoscape.bat -R 1234"
        )
        if str(mode).lower() == "on":
            raise DockingError(reason)
        return {
            "status": "xgmml_only",
            "reason": reason,
        }

    try:
        import py4cytoscape as p4c

        cyrest_url = _cyrest_url(base_url)
        p4c.cytoscape_ping(base_url=cyrest_url)
        nodes = pd.read_csv(nodes_csv)
        edges = pd.read_csv(edges_csv)
        stamp = time.strftime("%Y%m%d_%H%M%S")
        title = f"{network_title} {stamp}"
        collection = "Network toxicology"
        network_suid = p4c.create_network_from_data_frames(
            nodes=nodes,
            edges=edges,
            title=title,
            collection=collection,
            base_url=cyrest_url,
            node_id_list="node_id",
            source_id_list="source",
            target_id_list="target",
            interaction_type_list="edge_type",
        )
        style_name = f"Liver_CTPD_{stamp}"
        _apply_style(
            p4c,
            network_suid,
            style_name,
            cyrest_url,
            nodes,
            edges,
        )
        p4c.set_visual_style(
            style_name,
            network=network_suid,
            base_url=cyrest_url,
        )
        chosen_layout = _apply_layout(p4c, network_suid, layout, cyrest_url)
        try:
            p4c.fit_content(network=network_suid, base_url=cyrest_url)
        except Exception:
            pass

        png_path = out / "figures" / "ctpd_network_cytoscape.png"
        png_path.parent.mkdir(parents=True, exist_ok=True)
        _export_image(p4c, png_path, network_suid, cyrest_url)

        result: dict = {
            "status": "live",
            "network_suid": int(network_suid),
            "network_name": title,
            "collection": collection,
            "style_name": style_name,
            "layout": chosen_layout,
            "png": str(png_path) if png_path.exists() else "",
        }
        if save_session:
            session_path = out / "data" / "ctpd_cytoscape_session.cys"
            p4c.save_session(
                str(session_path.with_suffix("")),
                base_url=cyrest_url,
                overwrite_file=True,
            )
            result["session"] = str(session_path) if session_path.exists() else ""
        return result
    except Exception as exc:
        if str(mode).lower() == "on":
            raise DockingError(f"Cytoscape live export failed: {exc}") from exc
        LOG.warning("Cytoscape live export skipped: %s", exc)
        return {
            "status": "xgmml_only",
            "reason": str(exc),
        }


def _att_element(name: str, value: str, value_type: str) -> str:
    return (
        f"<att name={quoteattr(name)} value={quoteattr(value)} "
        f'type="{value_type}"/>'
    )


def _cyrest_url(base_url: str) -> str:
    root = str(base_url or "http://127.0.0.1:1234").rstrip("/")
    return root if root.endswith("/v1") else root + "/v1"


def _xgmml_type(column: str, value: str) -> str:
    lowered = str(column).strip().lower()
    if lowered in ("ppi_degree", "n_sources"):
        return "integer"
    if lowered in (
        "ppi_betweenness",
        "ppi_clustering",
        "ppi_hub_score",
        "combined_score",
    ):
        return "real"
    return "string"


def _apply_style(
    p4c,
    network_suid: int,
    style_name: str,
    base_url: str,
    nodes: pd.DataFrame,
    edges: pd.DataFrame,
) -> None:
    try:
        p4c.copy_visual_style("default", style_name, base_url=base_url)
    except Exception:
        p4c.create_visual_style(
            style_name,
            defaults=[
                {"visualProperty": "NODE_SIZE", "value": 45.0},
                {"visualProperty": "EDGE_WIDTH", "value": 2.0},
            ],
            mappings=[],
            base_url=base_url,
        )

    if "label" in nodes.columns:
        _style_call(
            lambda: p4c.set_node_label_mapping(
                "label",
                style_name=style_name,
                network=network_suid,
                base_url=base_url,
            )
        )
    if "node_type" in nodes.columns:
        _style_call(
            lambda: p4c.set_node_color_mapping(
                "node_type",
                table_column_values=["compound", "target", "disease"],
                colors=["#4C72B0", "#DD8452", "#C44E52"],
                mapping_type="d",
                default_color="#DD8452",
                style_name=style_name,
                network=network_suid,
                base_url=base_url,
            )
        )
        _style_call(
            lambda: p4c.set_node_shape_mapping(
                "node_type",
                table_column_values=["compound", "target", "disease"],
                shapes=["ROUND_RECTANGLE", "ELLIPSE", "HEXAGON"],
                default_shape="ELLIPSE",
                style_name=style_name,
                network=network_suid,
                base_url=base_url,
            )
        )
    if "ppi_degree" in nodes.columns:
        degree = pd.to_numeric(nodes["ppi_degree"], errors="coerce").fillna(0)
        upper = max(1.0, float(degree.max()))
        _style_call(
            lambda: p4c.set_node_size_mapping(
                "ppi_degree",
                table_column_values=[0.0, upper],
                sizes=[34.0, 110.0],
                mapping_type="c",
                default_size=45.0,
                style_name=style_name,
                network=network_suid,
                base_url=base_url,
            )
        )

    if "edge_type" in edges.columns:
        _style_call(
            lambda: p4c.set_edge_color_mapping(
                "edge_type",
                table_column_values=["compound_target", "disease_target", "ppi"],
                colors=["#4C72B0", "#C44E52", "#8C8C8C"],
                mapping_type="d",
                default_color="#8C8C8C",
                style_name=style_name,
                network=network_suid,
                base_url=base_url,
            )
        )
    if "edge_type" in edges.columns:
        _style_call(
            lambda: p4c.set_edge_line_width_mapping(
                "edge_type",
                table_column_values=["compound_target", "disease_target", "ppi"],
                widths=[3.0, 3.0, 2.0],
                mapping_type="d",
                default_width=2.0,
                style_name=style_name,
                network=network_suid,
                base_url=base_url,
            )
        )


def _style_call(call) -> None:
    try:
        call()
    except Exception as exc:
        LOG.warning("Cytoscape visual style update skipped: %s", exc)


def _apply_layout(p4c, network_suid: int, preferred: str, base_url: str) -> str:
    candidates = [preferred, "force-directed", "cose", "attribute-circle", None]
    errors: list[str] = []
    for candidate in candidates:
        try:
            if candidate is None:
                p4c.layout_network(
                    network=network_suid,
                    base_url=base_url,
                )
            else:
                p4c.layout_network(
                    layout_name=candidate,
                    network=network_suid,
                    base_url=base_url,
                )
            return str(candidate) if candidate else "preferred"
        except Exception as exc:
            errors.append(f"{candidate}: {exc}")
    LOG.warning("Cytoscape layout failed (%s); keeping default positions", "; ".join(errors))
    return "default"


def _export_image(
    p4c,
    png_path: Path,
    network_suid: int,
    base_url: str,
) -> None:
    for filename in (str(png_path.with_suffix("")), str(png_path)):
        try:
            p4c.export_image(
                filename=filename,
                type="PNG",
                network=network_suid,
                overwrite_file=True,
                base_url=base_url,
            )
            if png_path.exists():
                return
        except Exception:
            continue
